DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS USER;
CREATE TABLE ADDRESS(ADDRESS_ID INT PRIMARY KEY,STREET VARCHAR(200),CITY VARCHAR(30),ZIP_CODE VARCHAR(10));
INSERT INTO ADDRESS(ADDRESS_ID,STREET,CITY,ZIP_CODE) VALUES(1,'123 San Diego Lane','San Diego','92131');
INSERT INTO ADDRESS(ADDRESS_ID,STREET,CITY,ZIP_CODE) VALUES(2,'123 Los Angeles Lane','Los Angeles','90001');
CREATE TABLE USER(USER_ID INT PRIMARY KEY ,NAME VARCHAR(30),USERNAME VARCHAR(30),EMAIL VARCHAR(50),PHONE VARCHAR(12),ADDRESS_ID INT NOT NULL);
INSERT INTO USER(USER_ID,NAME,USERNAME,EMAIL,PHONE,ADDRESS_ID) VALUES(1,'Phillip Rivers','chargers01','philip@chargers.com','858-555-5555',1);
INSERT INTO USER(USER_ID,NAME,USERNAME,EMAIL,PHONE,ADDRESS_ID) VALUES(2,'Shaq Oneil','lakers01','shaq@lakers.com','202-555-5555',2);
